project:
  type: website

website:
  title: "Tom's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tomasjanikds
      - icon: linkedin
        href: https://www.linkedin.com/in/tomasjanik/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

